### PR TITLE
Fixed param error at decode/5

### PR DESCRIPTION
**Pull request by Dania02525**

### CODE REVIEW

**Comment by bryanjos** [comment]
Ah thanks! I've been meaning to give this another look lately, but I haven't had a lot of time. I saw your PR in the Joken repo and was confused as to what was going on, but looks like the issue was here. I'll try to update the hex version now while I'm thinking about it.

**Comment by Dania02525** [comment]
Yeah I was a bit confused with it too but I realized Token.decode was being called from the plug directly :-).  Is there any reason why all the config options aren't just pulled from the joken config? If we are decoding a jwt created by the same app the secret, algorithm, and json module should always be the same right?

**Comment by bryanjos** [comment]
The only reason is I didn't get around to it :). But that's exactly what I did in my latest commit. It'll read from the joken config block, but if the parameters are set on the plug, those will override the settings in the config block. 

I just want to look over it a bit more before I push it to hex.

Here is the commit if you are interested.
https://github.com/bryanjos/plug_jwt/commit/d5b18cec8a20b87ec59690a61901c26aeddfde25

**Comment by Dania02525** [comment]
This is a nice module- appreciate your work on it!

**Pull request merged**
